[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2021"
name = "memestat"
version = "0.1.0"

[dependencies]
average = "0.13.1"
derive_more = "0.99.17"
eyre = "0.6.7"
mathru = "0.12.0"
rand = "0.8.5"
